version: "3.7"
services:
  app:
    tty: true
    build:
      context: ./
      dockerfile: Dockerfile
    image: corexc
    container_name: corexc-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - corexc

  nginx:
    image: nginx:alpine
    container_name: corexc-nginx
    restart: unless-stopped
    ports:
      - 5000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - corexc

networks:
  corexc:
    driver: bridge